package apply

import "testing"

/*
TC-APPLY-PARSER-001
Type: Positive
Title: Quoted values with spaces
Summary:
Checks that renderer-style quoted values are tokenized safely.
The parser should preserve the original trimmed command line in the plan.

Validates:
  - Single-quoted values with spaces are accepted
  - Double-quoted values with spaces are accepted
  - Original command text is preserved after validation
*/
func TestParseCommandsAllowsQuotedValuesWithSpaces(t *testing.T) {
	input := stringsJoinLines(
		"set interfaces bridge br1 description 'LAN Network'",
		`set interfaces ethernet eth0 description "WAN uplink"`,
	)

	got, err := parseCommands(input)
	assertNoApplyError(t, err)
	assertStringSlicesEqual(t, got, []string{
		"set interfaces bridge br1 description 'LAN Network'",
		`set interfaces ethernet eth0 description "WAN uplink"`,
	})
}

/*
TC-APPLY-PARSER-002
Type: Negative
Title: Unclosed quotes
Summary:
Passes commands with unterminated single and double quotes.
The parser must reject both forms before planning can continue.

Validates:
  - Unclosed single quotes are rejected
  - Unclosed double quotes are rejected
  - Failures use invalid_command
*/
func TestParseCommandsRejectsUnclosedQuotes(t *testing.T) {
	tests := []string{
		"set interfaces bridge br1 description 'LAN Network",
		`set interfaces ethernet eth0 description "WAN uplink`,
	}

	for _, input := range tests {
		_, err := parseCommands(input)
		assertApplyCode(t, err, CodeInvalidCommand)
	}
}

/*
TC-APPLY-PARSER-003
Type: Positive
Title: CRLF and blank lines
Summary:
Verifies that CRLF input is normalized and blank lines are ignored.
Trailing spaces are trimmed per command line before returning the plan input.

Validates:
  - CRLF input is accepted
  - Blank lines are ignored
  - Returned set commands are trimmed
*/
func TestParseCommandsNormalizesCRLFAndIgnoresBlankLines(t *testing.T) {
	input := "\r\n set interfaces bridge br0 address dhcp  \r\n\r\nset nat source rule 100 translation address masquerade\r\n"

	got, err := parseCommands(input)
	assertNoApplyError(t, err)
	assertStringSlicesEqual(t, got, []string{
		"set interfaces bridge br0 address dhcp",
		"set nat source rule 100 translation address masquerade",
	})
}

/*
TC-APPLY-PARSER-004
Type: Negative
Title: Comment lines
Summary:
Passes a renderer output line that begins with a comment marker.
Comments are rejected because renderer output must be command text only.

Validates:
  - Comment lines are not ignored
  - Comment rejection happens during parsing
  - Failures use invalid_command
*/
func TestParseCommandsRejectsComments(t *testing.T) {
	_, err := parseCommands("# generated by renderer\nset interfaces bridge br0 address dhcp\n")
	assertApplyCode(t, err, CodeInvalidCommand)
}

/*
TC-APPLY-PARSER-005
Type: Negative
Title: Unsafe metacharacters
Summary:
Checks shell and control metacharacter rejection across command lines.
The same rejection applies even when a character appears inside quotes.

Validates:
  - Shell separators are rejected
  - Command substitution markers are rejected
  - Quoted unsafe characters are rejected
*/
func TestParseCommandsRejectsUnsafeMetacharacters(t *testing.T) {
	tests := []string{
		"set nat source rule 100 translation address masquerade; commit",
		"set nat source rule 100 translation address `whoami`",
		"set nat source rule 100 translation address $(whoami)",
		"set interfaces bridge br1 description 'LAN > WAN'",
	}

	for _, input := range tests {
		_, err := parseCommands(input)
		assertApplyCode(t, err, CodeInvalidCommand)
	}
}

/*
TC-APPLY-PARSER-006
Type: Negative
Title: Non-set operations
Summary:
Passes common VyOS and shell-style operations instead of renderer set commands.
The apply package must reject them before executor invocation.

Validates:
  - Commit and save operations are rejected
  - Delete and show operations are rejected
  - Failures use invalid_command
*/
func TestParseCommandsRejectsNonSetOperations(t *testing.T) {
	tests := []string{
		"commit",
		"save",
		"delete nat source",
		"show configuration",
		"sudo set system host-name router1",
	}

	for _, input := range tests {
		_, err := parseCommands(input)
		assertApplyCode(t, err, CodeInvalidCommand)
	}
}

/*
TC-APPLY-PARSER-007
Type: Negative
Title: Unsupported set paths
Summary:
Passes set commands for roots outside the MVP renderer/apply allowlist.
Protected or future roots must not be accepted implicitly.

Validates:
  - System and unsupported service paths are rejected
  - Users and protocols paths are rejected
  - Failures use invalid_command
*/
func TestParseCommandsRejectsUnsupportedSetPaths(t *testing.T) {
	tests := []string{
		"set system host-name router1",
		"set service ssh disable-password-authentication",
		"set service https listen-address 192.0.2.1",
		"set users user admin authentication plaintext-password test",
		"set protocols static route 0.0.0.0/0 next-hop 1.1.1.1",
	}

	for _, input := range tests {
		_, err := parseCommands(input)
		assertApplyCode(t, err, CodeInvalidCommand)
	}
}

/*
TC-APPLY-SERVICE-001
Type: Mixed
Title: Exact service command allowlist
Summary:
Checks the exact service command shapes emitted by the renderer. The parser
should accept DHCP, DNS forwarding, and SSH port commands while keeping service
validation narrow.

Validates:
  - Renderer DHCP command shapes are accepted
  - Renderer DNS forwarding command shapes are accepted
  - Renderer SSH port command shape is accepted
*/
func TestParseCommandsAllowsRendererServicePaths(t *testing.T) {
	input := stringsJoinLines(
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 lease 21600",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option default-router 192.168.50.1",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option name-server 192.168.50.1",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option domain-name vyos.net",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 range 0 start 192.168.50.10",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 range 0 stop 192.168.50.137",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 subnet-id 4052",
		"set service dns forwarding allow-from 192.168.50.0/24",
		"set service dns forwarding cache-size 0",
		"set service dns forwarding listen-address 192.168.50.1",
		"set service ssh port 22",
	)
	got, err := parseCommands(input)
	assertNoApplyError(t, err)
	assertStringSlicesEqual(t, got, []string{
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 lease 21600",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option default-router 192.168.50.1",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option name-server 192.168.50.1",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option domain-name vyos.net",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 range 0 start 192.168.50.10",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 range 0 stop 192.168.50.137",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 subnet-id 4052",
		"set service dns forwarding allow-from 192.168.50.0/24",
		"set service dns forwarding cache-size 0",
		"set service dns forwarding listen-address 192.168.50.1",
		"set service ssh port 22",
	})
}

/*
TC-APPLY-SERVICE-002
Type: Negative
Title: Unsupported service command rejection
Summary:
Passes broad or unsupported service subpaths that are not emitted by the
renderer. The apply parser must reject them before planning or executor use.

Validates:
  - Broad DHCP and DNS service paths are rejected
  - Unsupported SSH subcommands are rejected
  - Invalid IP, prefix, and integer fields are rejected
*/
func TestParseCommandsRejectsUnsupportedServicePaths(t *testing.T) {
	tests := []string{
		"set service dhcp-server global-parameters 'option foo'",
		"set service dhcp-server shared-network-name LAN authoritative",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option router 192.168.50.1",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 option default-router 2001:db8::1",
		"set service dhcp-server shared-network-name LAN subnet 2001:db8::/64 lease 21600",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 lease 0",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 range 1 start 192.168.50.10",
		"set service dhcp-server shared-network-name LAN subnet 192.168.50.0/24 subnet-id 0",
		"set service dns forwarding system",
		"set service dns forwarding name-server 1.1.1.1",
		"set service dns forwarding allow-from 2001:db8::/64",
		"set service dns forwarding cache-size 1",
		"set service dns forwarding listen-address 2001:db8::1",
		"set service ssh port 0",
		"set service ssh port 65536",
		"set service ssh disable-password-authentication",
		"set service ssh listen-address 192.168.1.1",
		"set service ntp server pool.ntp.org",
		"set service",
	}
	for _, input := range tests {
		_, err := parseCommands(input)
		assertApplyCode(t, err, CodeInvalidCommand)
	}
}

/*
TC-APPLY-PARSER-008
Type: Mixed
Title: Ethernet description allowlist
Summary:
Verifies the only supported preserved-root ethernet path.
Description commands are accepted while address and MTU changes are rejected.

Validates:
  - Ethernet description commands are accepted
  - Ethernet address commands are rejected
  - Ethernet MTU commands are rejected
*/
func TestParseCommandsAllowsEthernetDescriptionOnly(t *testing.T) {
	got, err := parseCommands("set interfaces ethernet eth0 description 'WAN uplink'\n")
	assertNoApplyError(t, err)
	assertStringSlicesEqual(t, got, []string{"set interfaces ethernet eth0 description 'WAN uplink'"})

	for _, input := range []string{
		"set interfaces ethernet eth0 address dhcp",
		"set interfaces ethernet eth0 mtu 1500",
	} {
		_, err := parseCommands(input)
		assertApplyCode(t, err, CodeInvalidCommand)
	}
}
